version: '3.8'
services:
  frontend:
    image: node:18
    working_dir: /workspace/frontend
    volumes:
      - .:/workspace
    command: npm start
    ports:
      - "3000:3000"

  backend:
    image: node:18
    working_dir: /workspace/backend
    volumes:
      - .:/workspace
    command: npm start
    ports:
      - "4000:4000"
